### ISSUE TITLE
Firmware source code

### ISSUE THREAD

**Issue by MarchenkoOleg** [ofdl-robotics-tw/EV3-FirmwareDev-VM#1]
Hello. Could you fill in the lms2012 source code so as not to download the entire VM image?

**Comment by a10036gt** [comment]
You can download lms2012 source code from LEGO website:
[https://education.lego.com/en-us/product-resources/mindstorms-ev3/downloads/developer-kits/](https://education.lego.com/en-us/product-resources/mindstorms-ev3/downloads/developer-kits/)
or here for old version:
[https://github.com/mindboards/ev3sources](https://github.com/mindboards/ev3sources)

**Comment by MarchenkoOleg** [comment]
Have you made any changes compared to the source code from the Lego website?
If you would share information about how you modified the firmware for the operation of the block https://github.com/a10036gt/EV3-BatteryInfo-Block That would be great.

**Comment by a10036gt** [comment]
Base on v1.07x, 
Add battery view apps.
Remove Demo program.
Add some custom opUI get cmd:
![image](https://github.com/user-attachments/assets/279da6aa-0536-42b0-9f6e-46a7e9d0d747)
![image](https://github.com/user-attachments/assets/2620d681-8f8a-4a92-a421-4513bbbf0542)
![image](https://github.com/user-attachments/assets/86cf6c51-107b-4e43-9ac7-0da68dae7df3)
